
# Change the default Omarchy look'n'feel

layerrule {
  name = layerrule-1
  no_anim = on
  match:namespace = gtk4-layer-shell
}

layerrule {
  name = layerrule-2
  no_anim = on
  match:namespace = switcharoo_switch
}

layerrule {
  name = layerrule-3
  no_anim = on
  match:namespace = swayosd
}

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master

    border_size = 4
    col.active_border = rgb(d14d41) rgb(da702c) 45deg
    col.inactive_border = rgb(575653)
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
}

animations {
    enabled = true
    animation = windowsMove, 1, 1, default
}

# Allow restarting hyprlock if it crashes during sleep/resume
misc {
    allow_session_lock_restore = true
}
