# windowrulev2 = workspace empty, floating:0

windowrulev2 = workspace unset, class:^(org\.gnome\.Nautilus)$
windowrulev2 = workspace unset, class:^(Bitwarden)$

# Keep background apps in special workspace
windowrulev2 = workspace special:background silent, class:^(nz\.co\.mega\.megasync)$
windowrulev2 = workspace special:background, class:^(org\.kde\.kdeconnect\.app)$

# Calendar reminders
windowrulev2 = size 400 300, class:^(org\.mozilla\.Thunderbird)$, initialTitle:^(Calendar Reminders)$
windowrulev2 = pin, class:^(org\.mozilla\.Thunderbird)$, initialTitle:^(Calendar Reminders)$
windowrulev2 = float, class:^(org\.mozilla\.Thunderbird)$, initialTitle:^(Calendar Reminders)$


# BTOP
windowrulev2 = float, class:^(org\.omarchy\.btop)$
windowrulev2 = size 40% 60%, class:^(org\.omarchy\.btop)$
