
################################
# Workspace assignment
################################

# Nautilus & Bitwarden: no forced workspace
windowrule = match:class org.gnome.Nautilus, workspace unset
windowrule = match:class Bitwarden, workspace unset

################################
# Background apps → special workspace
################################

# MEGA Sync (silent)
windowrule = match:class nz.co.mega.megasync, workspace special:background silent


################################
# Thunderbird – Calendar Reminders
################################

windowrule = match:class org.mozilla.Thunderbird, match:initial_title Calendar Reminders, float on
windowrule = match:class org.mozilla.Thunderbird, match:initial_title Calendar Reminders, pin on
windowrule = match:class org.mozilla.Thunderbird, match:initial_title Calendar Reminders, size 400 300
