# wl-kbptr hotkeys
unbind = SUPER ALT, F
bindd = SUPER ALT, F, Mouse hints (floating), exec, wl-kbptr -o modes=floating,click
bindd = SUPER ALT, X, Mouse hints (tile), exec, wl-kbptr -o modes=tile,click
bindd = SUPER ALT, B, Split mode (tile), exec, wl-kbptr -o modes=split,click
bind = SUPER ALT, C, exec, hyprctl keyword cursor:inactive_timeout 0; hyprctl keyword cursor:hide_on_key_press false; hyprctl dispatch submap cursor

# Cursor submap (similar to the Mouse mode in Sway)
submap = cursor

# Jump chttp://localhost:5173/auth/loginursor to a position
bind=,x,exec,hyprctl dispatch submap reset && wl-kbptr && hyprctl dispatch submap cursor
bind=,b,exec,hyprctl dispatch submap reset && wl-kbptr -o modes=bisect,click && hyprctl dispatch submap cursor

# Cursor movement (normal speed)
binde=,j,exec,wlptrctl move 0 15
binde=,k,exec,wlptrctl move 0 -15
binde=,l,exec,wlptrctl move 15 0
binde=,h,exec,wlptrctl move -15 0

# Cursor movement (fast speed with Shift)
binde=SHIFT,j,exec,wlptrctl move 0 200
binde=SHIFT,k,exec,wlptrctl move 0 -200
binde=SHIFT,l,exec,wlptrctl move 200 0
binde=SHIFT,h,exec,wlptrctl move -200 0

# Left button
binde=,z,exec,wlptrctl button left click
# Middle button
binde=,x,exec,wlptrctl button middle click
# Right button
binde=,c,exec,wlptrctl button right click

# Drag (hold left button down / release)
binde=,e,exec,wlptrctl button left press
binde=,r,exec,wlptrctl button left release
binde=,t,exec,wlptrctl button middle press
binde=,y,exec,wlptrctl button middle release

# Scroll up and down
binde=,d,exec,wlptrctl scroll 1 0
binde=,u,exec,wlptrctl scroll -1 0

# Scroll left and right
binde=,b,exec,wlptrctl scroll 0 -1
binde=,f,exec,wlptrctl scroll 0 1

# Exit cursor submap
bind=,escape,exec,hyprctl keyword cursor:inactive_timeout 3; hyprctl keyword cursor:hide_on_key_press true; hyprctl dispatch submap reset 

bind = , escape, submap, reset


submap = reset
