local harpoon = require("harpoon")
harpoon:setup()

vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
end)
vim.keymap.set("n", "<C-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set("n", "<leader>h", function()
	harpoon:list():select(1)
end)
vim.keymap.set("n", "<leader>j", function()
	harpoon:list():select(2)
end)
vim.keymap.set("n", "<leader>k", function()
	harpoon:list():select(3)
end)
vim.keymap.set("n", "<leader>l", function()
	harpoon:list():select(4)
end)

-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set("n", "<M-[>", function()
	harpoon:list():prev()
end)
vim.keymap.set("n", "<M-]>", function()
	harpoon:list():next()
end)

-- local mark = require("harpoon.mark")
-- local ui = require("harpoon.ui")
--
-- vim.keymap.set("n", "<leader>a", mark.add_file)
-- vim.keymap.set("n", "<C-e>", function()
-- 	ui.toggle_quick_menu()
-- 	-- Find a way to trigger toggle_keymaps when Harpoon is closed, regardless
-- 	-- of how it is closed.
-- 	-- toggle_keymaps()
-- end)
-- vim.keymap.set("n", "<leader>h", function()
-- 	ui.nav_file(1)
-- end)
-- vim.keymap.set("n", "<leader>j", function()
-- 	ui.nav_file(2)
-- end)
-- vim.keymap.set("n", "<leader>k", function()
-- 	ui.nav_file(3)
-- end)
-- vim.keymap.set("n", "<leader>l", function()
-- 	ui.nav_file(4)
-- end)
