-- local prettier = require("prettier")
--
-- prettier.setup({
-- 	bin = "prettierd",
-- 	filetypes = {
-- 		"css",
-- 		"graphql",
-- 		"html",
-- 		"json",
-- 		"jsonc",
-- 		"less",
-- 		"markdown",
-- 		"scss",
-- 		"yaml",
-- 		"liquid",
-- 	},
-- })
